version: '3'
services:
  serverless:
    build: ./sls-villains
    ports:
    - "3100:3000"
    links:
    - db
    environment:
    - DB=mongodb://db:27017/db-HeroesAndVillains
    - PORT=3100
    networks:
    - projectHeroesAndVillains

  map:
    build: ./map
    ports:
    - "3200:3200"
    environment:
      - PORT=3200
      - SLS=http://serverless:3000
    networks:
    - projectHeroesAndVillains

  hero:
    build: ./hero
    ports:
      - "3300:3300"
    environment:
      - PORT=3300
      - SLS=http://serverless:3000
      - MAP=http://map:3200
      - NAME=Macron
      - X=0
      - Y=0
    networks:
    - projectHeroesAndVillains

  hero2:
    build: ./hero
    ports:
    - "3500:3500"
    environment:
    - PORT=3500
    - SLS=http://serverless:3000
    - MAP=http://map:3200
    - NAME=Benalla
    - X=50
    - Y=50
    networks:
    - projectHeroesAndVillains

  interface:
    build: ./interface
    ports:
      - "4200:4200"
    environment:
      - SLS=http://serverless:3000
    networks:
    - projectHeroesAndVillains

  db:
    image: mongo
    ports:
    - "27017:27017"
    networks:
    - projectHeroesAndVillains

networks:
  projectHeroesAndVillains: