service: serverless-villains

provider:
  name: aws
  runtime: nodejs8.10

functions:
  findAllVillains:
    handler: findAllVillains.villainsHandler
    events:
      - http: GET /getAllVillains

  deleteVillains:
    handler: deleteVillains.deleteVillainsHandler
    events:
    - http: POST /deleteVillains

  heroes:
    handler: findAllHeroes.heroesHandler
    events:
      - http: GET /getAllHeroes

  getTarget:
    handler: getTarget.getTargetHandler
    events:
      - http: POST /getTarget

plugins:
- serverless-offline
