service: serverless-villains

provider:
  name: aws
  runtime: nodejs8.10

functions:
  findAllVillains:
    handler: find-all-villains.findAllVillainsHandler
    events:
    - http: GET /getAllVillains

  createVillains:
    handler: create-villains.createVillainsHandler
    events:
    - http: POST /createVillain

  createHero:
    handler: create-hero.createHeroHandler
    events:
    - http: POST /createHero

  deleteVillains:
    handler: delete-villains.deleteVillainsHandler
    events:
    - http: POST /deleteVillain

  findAllHeroes:
    handler: find-all-heroes.findAllHeroesHandler
    events:
    - http: GET /getAllHeroes

  getTargetForHeroes:
    handler: get-target.getTargetHandler
    events:
    - http: POST /getTarget

  updateVillains:
    handler: update-villains.updateVillainHandler
    events:
    - http: POST /updateVillain

  updateHero:
    handler: update-hero.updateHeroHandler
    events:
    - http: POST /updateHero

plugins:
- serverless-offline
