service: serverless-villains

provider:
  name: aws
  runtime: nodejs8.10

functions:
  villains:
    handler: findAllVillains.villainsHandler
    events:
      - http: GET /getAllVillains

  heroes:
    handler: findAllHeroes.heroesHandler
    events:
      - http: GET /getAllHeroes

plugins:
- serverless-offline
