service: serverless-villains

provider:
  name: aws
  runtime: nodejs8.10

functions:
  findAllVillains:
    handler: findAllVillains.findAllVillainsHandler
    events:
      - http: GET /getAllVillains

  createVillains:
    handler: createVillains.createVillainsHandler
    events:
      - http: POST /createVillains

  deleteVillains:
    handler: deleteVillains.deleteVillainsHandler
    events:
    - http: POST /deleteVillains

  findAllHeroes:
    handler: findAllHeroes.findAllHeroesHandler
    events:
      - http: GET /getAllHeroes

  getTargetForHeroes:
    handler: getTarget.getTargetHandler
    events:
      - http: POST /getTarget

plugins:
- serverless-offline
